language: cpp

git:
  depth: 3

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.9
      - clang-4.0
      - clang-5.0
      
matrix:
  include:
    - os: linux
      sudo: false
      env: CXX="g++-4.9"
      compiler: gcc
    - os: linux
      sudo: false
      env: CXX="g++-5"
      compiler: gcc
    - os: linux
      sudo: false
      env: CXX="g++-6"
      compiler: gcc
    - os: linux
      sudo: false
      env: CXX="clang++-3.9"
      compiler: clang
    - os: linux
      sudo: false
      env: CXX="clang++-4.0"
      compiler: clang
    - os: linux
      sudo: false
      env: CXX="clang++-5.0"
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode8
  
script: 
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

notifications:
  email:
    recipients:
      - jeffamstutz@gmail.com
    on_success: always
    on_failure: always