language: cpp

git:
  depth: 3

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.9
      - clang-4.0
      - clang-5.0
      
matrix:
  include:
    - os: linux
      sudo: false
      env: CMAKE_OPTIONS="-DCMAKE_CXX_COMPILER=g++-4.9"
      compiler: gcc
    - os: linux
      sudo: false
      env: CMAKE_OPTIONS="-DCMAKE_CXX_COMPILER=g++-5"
      compiler: gcc
    - os: linux
      sudo: false
      env: CMAKE_OPTIONS="-DCMAKE_CXX_COMPILER=g++-6"
      compiler: gcc
    - os: linux
      sudo: false
      env: CMAKE_OPTIONS="-DCMAKE_CXX_COMPILER=clang++-3.9"
      compiler: clang
    - os: linux
      sudo: false
      env: CMAKE_OPTIONS="-DCMAKE_CXX_COMPILER=clang++-4.0"
      compiler: clang
    - os: linux
      sudo: false
      env: CMAKE_OPTIONS="-DCMAKE_CXX_COMPILER=clang++-5.0"
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode8
  
script: 
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} ..
  - cmake --build .
  - ctest .

notifications:
  email:
    recipients:
      - jeffamstutz@gmail.com
    on_success: always
    on_failure: always